// ============================================================
// 内置工具：制作 PDF（make_pdf）
// ============================================================
//
// 功能：生成精美排版的 PDF/HTML 可视化报告文档
//
// ============================================================

import { z } from "zod";
import type { ToolDefinition } from "../types";
import fs from "fs";
import path from "path";
import { nanoid } from "nanoid";

const makePdfSchema = z.object({
  title: z.string().describe("PDF 文件标题，例如 '公司季度业务数据分析报告'"),
  content: z.string().describe("PDF 文件的正文内容，支持富文本及段落表达"),
  theme: z.enum(["default", "dark", "warm", "ocean"]).default("default").describe("排版主题色彩风格：default(经典白), dark(极客黑), warm(复古暖), ocean(清新蓝)"),
});

type MakePdfInput = z.infer<typeof makePdfSchema>;

export const makePdfTool: ToolDefinition<MakePdfInput> = {
  name: "make_pdf",
  description: "制作并生成精美排版的 PDF 格式文档。输入标题和内容，工具会自动进行高级主题排版并生成下载与打印链接。",
  parameters: makePdfSchema,
  execute: async (input, _context) => {
    try {
      const downloadDir = path.join(process.cwd(), "public", "downloads");
      if (!fs.existsSync(downloadDir)) {
        fs.mkdirSync(downloadDir, { recursive: true });
      }

      const fileId = nanoid(8);
      const fileName = `pdf-${fileId}.html`; // 渲染为高保真 HTML 格式，以便浏览器能直接打印成 PDF
      const filePath = path.join(downloadDir, fileName);

      // 精美主题配色样式
      const themeClasses = {
        default: "bg-white text-slate-800 border-slate-200",
        dark: "bg-slate-900 text-slate-100 border-slate-800",
        warm: "bg-amber-50/40 text-amber-950 border-amber-200",
        ocean: "bg-sky-50/40 text-sky-950 border-sky-200",
      }[input.theme];

      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${input.title}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    @media print {
      .no-print { display: none !important; }
      body { background: white !important; color: black !important; }
    }
  </style>
</head>
<body class="p-8 ${themeClasses} min-h-screen font-sans">
  <div class="max-w-3xl mx-auto space-y-6">
    <div class="flex justify-between items-center border-b pb-4">
      <div>
        <h1 class="text-2xl font-black tracking-tight">${input.title}</h1>
        <p class="text-[10px] text-slate-500 mt-1">Generated by OpenCat AI Toolset on ${new Date().toLocaleDateString()}</p>
      </div>
      <button onclick="window.print()" class="no-print flex items-center gap-1 rounded-lg bg-indigo-600 px-3.5 py-1.5 text-xs font-semibold text-white hover:bg-indigo-500 transition-colors shadow">
        🖨️ 打印为 PDF
      </button>
    </div>
    <div class="prose prose-slate max-w-none text-sm leading-relaxed whitespace-pre-wrap mt-6">
      ${input.content}
    </div>
  </div>
</body>
</html>
      `;

      fs.writeFileSync(filePath, htmlContent, "utf-8");

      return {
        success: true,
        data: {
          title: input.title,
          fileName,
          downloadUrl: `/downloads/${fileName}`,
          message: "PDF 电子文档已生成。您可以点击下载链接访问，并在页面右上角一键『打印为 PDF』保存到本地。",
        },
      };
    } catch (err) {
      return {
        success: false,
        error: `生成 PDF 失败: ${err instanceof Error ? err.message : "未知错误"}`,
      };
    }
  },
};
